[project]
name = "google-apis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hangsik Shin", email = "shins777@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "googlemaps>=4.10.0",
    "ipykernel>=7.3.0",
    "pandas>=3.0.5",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[project.scripts]
google-apis = "google_apis:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
